### PR TITLE
feat(WIP): blog + blog post pages

### PR DESCRIPTION
**Pull request by nicholaswma**
Placeholder for static blog

WIP: Will be breaking up blog.tsx into reusable components

### CODE REVIEW

**Comment by maximousblk** [comment]
#### 📝 Changed routes:


| [**/blog/\[id\]**](https://landing-81n65sngp-th8ta.vercel.app/blog/[id]) | [**/blog**](https://landing-81n65sngp-th8ta.vercel.app/blog) |
|:-:|:-:|
|<a href="https://landing-81n65sngp-th8ta.vercel.app/blog/[id]">Screenshot of /blog/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/NcVRVzjMb6hVpdIBPq4SdoTRMvoFSgBTq-7eMo8tTWcu5lcY8heMud7Dy3PSW5nCKL0z4WjvBqetGxUYfPwryg.png">(view full size)</a> |<a href="https://landing-81n65sngp-th8ta.vercel.app/blog">Screenshot of /blog</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/argWgCydJzPL9_l1KnKms3BfZjAwNrywOVEOAb0CuJ68d5rqvCwNyFFvdH-J2Ql8f2_bWWdRauVUj5LYRnn58A.png">(view full size)</a> |







Commit 651adf21ebee118e32b2154a640edd3b70d37f11 (https://landing-81n65sngp-th8ta.vercel.app).

**Comment by martonlederer** [comment]
Is this ready for review?

**Comment by nicholaswma** [comment]
> Is this ready for review?

@martonlederer just been trying to make more reusable components, but should be fine for reviewing now

**Comment by martonlederer** [comment]
Sounds good, will review today

**Review by martonlederer — APPROVED** [review]
LGTM! Really awesome implementation.
Only thing remaining is that the date looks a bit weird on mobile, when viewing a blog. Could you fix that? After that's done, feel free to merge.image

**Comment by nicholaswma** [comment]
@martonlederer ahh thanks!

https://landing-cm0grhics-th8ta.vercel.app/blog

does this link show the distorted date pill? I haven't been able to replicate it on my end

**Comment by martonlederer** [comment]
It's on the blog article view:

https://landing-cm0grhics-th8ta.vercel.app/blog/123

**Comment by nicholaswma** [comment]
> It's on the blog article view:
> 
> https://landing-cm0grhics-th8ta.vercel.app/blog/123

oops, taking care of this!

**Pull request merged**
